---

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "reboot"
    labels:
      - component:environment
      - type:improvement
      - priority:low
