---

name: ci

on:
  push:
    branches:
      - 'main'
      - 'reboot'
    tags:
      - '*'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.5.2

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Install Nix Dependencies
        run: nix develop --command true

      - name: Build Software
        run: nix develop --command make

      - name: Check Sync of Files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            printf 'Files are not in sync: building changed some:\n'
            git diff
            exit 1
          fi

      - name: Test Software
        run: nix develop --command make test
